[package]
name = "time_for_food"
version = "0.1.0"
authors = ["Nathan McCarty <nathan@mccarty.io>"]

[dependencies]
num = "0.1"
num-rational = "0.1"
fluent = "0.2.0"
serde ="1.0"
serde_json = "1.0"
serde_derive = "1.0"
rouille = "2.1"
chrono = { version = "0.4", features = ["serde"] }
